### ISSUE TITLE
Loading filters failed: HTTP 500 Firefish

### ISSUE THREAD

**Issue by KaiserCalm** [pachli/pachli-android#248]
**Describe the bug**
A clear and concise description of what it is.
 - Opening the app or really anything in the app afterwards triggers this error.

**To Reproduce**
1. Open the app.

**Expected behavior**
 - The error would not be present.

**Screenshots or video**
If applicable, please add screenshots or video to help explain your problem.
![Screenshot_20231112-135001_Pachli](https://github.com/pachli/pachli-android/assets/81613945/ddb40da6-34e4-4328-95c5-d7bfd687ec43)
![Screenshot_20231112-135022_Pachli](https://github.com/pachli/pachli-android/assets/81613945/7f1e27a8-7d15-421f-8679-c1c2352b77e5)

**Versions**
Please include the version of Pachli and Android you are using, and the software version your server is using. Find this on the Pachli "About" screen.
> Pachli 1.4.0
> 
> Device:
> 
> Android version: 13
> SDK level: 33
> 
> Account:
> 
> @deivpaukst@stop.voring.me
> Version: 3.0.0 (compatible; Firefish 1.0.4-beta31)

**Additional context**

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.
 - Yes

**Comment by ProjectMoon** [comment]
This appears to be a server-side problem, as this is what happens when attempting to access the filters API via Pachli on my Firefish server:

```
    at new NoImplementedError (/firefish/packages/megalodon/lib/src/megalodon.js:66:28)
    at /firefish/packages/megalodon/lib/src/misskey.js:1003:35
    at new Promise (<anonymous>)
    at Misskey.<anonymous> (/firefish/packages/megalodon/lib/src/misskey.js:1002:28)
    at step (/firefish/packages/megalodon/lib/src/misskey.js:44:23)
    at Object.next (/firefish/packages/megalodon/lib/src/misskey.js:25:53)
    at /firefish/packages/megalodon/lib/src/misskey.js:19:71
    at new Promise (<anonymous>)
    at __awaiter (/firefish/packages/megalodon/lib/src/misskey.js:15:12)
    at Misskey.getFilters (/firefish/packages/megalodon/lib/src/misskey.js:1000:16)
    at file:///firefish/packages/backend/built/server/api/mastodon/endpoints/filter.js:11:39
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /firefish/node_modules/.pnpm/@koa+router@9.0.1/node_modules/@koa/router/lib/router.js:363:16
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at file:///firefish/packages/backend/built/server/api/index.js:110:11
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /firefish/node_modules/.pnpm/@koa+router@9.0.1/node_modules/@koa/router/lib/router.js:363:16
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /firefish/node_modules/.pnpm/koa-body@6.0.1/node_modules/koa-body/lib/index.js:115:16
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /firefish/node_modules/.pnpm/@koa+router@9.0.1/node_modules/@koa/router/lib/router.js:363:16
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at dispatch (/firefish/node_modules/.pnpm/@koa+router@9.0.1/node_modules/@koa/router/lib/router.js:368:31)
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at dispatch (/firefish/node_modules/.pnpm/@koa+router@9.0.1/node_modules/@koa/router/lib/router.js:349:32)
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at file:///firefish/packages/backend/built/server/api/index.js:34:11
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at cors (/firefish/node_modules/.pnpm/@koa+cors@3.4.3/node_modules/@koa/cors/index.js:61:38)
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at /firefish/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:58:11
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at file:///firefish/packages/backend/built/server/index.js:61:15
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at cors (/firefish/node_modules/.pnpm/@koa+cors@3.4.3/node_modules/@koa/cors/index.js:61:38)
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /firefish/node_modules/.pnpm/koa-remove-trailing-slashes@2.0.3/node_modules/koa-remove-trailing-slashes/index.js:20:19
    at dispatch (/firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:42:32)
    at /firefish/node_modules/.pnpm/koa-compose@4.1.0/node_modules/koa-compose/index.js:34:12
    at Application.handleRequest (/firefish/node_modules/.pnpm/koa@2.14.2/node_modules/koa/lib/application.js:186:12)
    at Server.handleRequest (/firefish/node_modules/.pnpm/koa@2.14.2/node_modules/koa/lib/application.js:157:21)
    at Server.emit (node:events:514:28)
    at Server.emit (node:domain:489:12)
    at parserOnIncoming (node:_http_server:1132:12)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)

  TypeError: Cannot read properties of undefined (reading 'data')
      at file:///firefish/packages/backend/built/server/api/mastodon/endpoints/filter.js:16:35
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///firefish/packages/backend/built/server/api/index.js:110:5
      at async file:///firefish/packages/backend/built/server/api/index.js:34:5
      at async cors (/firefish/node_modules/.pnpm/@koa+cors@3.4.3/node_modules/@koa/cors/index.js:61:32)
      at async /firefish/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:58:5
      at async file:///firefish/packages/backend/built/server/index.js:61:9
      at async cors (/firefish/node_modules/.pnpm/@koa+cors@3.4.3/node_modules/@koa/cors/index.js:61:32)
```

File in question: https://git.joinfirefish.org/firefish/firefish/-/blob/develop/packages/backend/src/server/api/mastodon/endpoints/filter.ts
