### ISSUE TITLE
pachli currrent not opening after change `refactor: Convert from Gson to Moshi`

### ISSUE THREAD

**Issue by foss-** [pachli/pachli-android#433]
Pachli Current 2.2.0+a3d45ca9
Android 13.1

Happens when right after opening Pachli Current. It closes and shows the report dialog.
Breaking change: https://github.com/pachli/pachli-android/pull/428

<details>
  <summary>stack trace</summary>
STACK_TRACE=com.squareup.moshi.JsonDataException: Required value 'html' missing at $
at com.squareup.moshi.internal.Util.e(SourceFile:44)
at app.pachli.core.network.model.CardJsonAdapter.fromJson(SourceFile:32)
at app.pachli.core.network.model.CardJsonAdapter.fromJson(SourceFile:1)
at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(SourceFile:16)
at com.squareup.moshi.JsonAdapter.fromJson(SourceFile:3)
at app.pachli.core.database.model.TimelineStatusWithAccount.a(SourceFile:232)
at app.pachli.viewdata.StatusViewData$Companion.a(SourceFile:1)
at app.pachli.components.timeline.viewmodel.CachedTimelineViewModel$getStatuses$1$1.x(SourceFile:34)
at app.pachli.components.timeline.viewmodel.CachedTimelineViewModel$getStatuses$1$1.k(SourceFile:13)
at androidx.paging.PageEvent$Insert.b(SourceFile:186)
at androidx.paging.PagingDataTransforms$map$$inlined$transform$1$2.a(SourceFile:70)
at kotlinx.coroutines.flow.FlowKt__TransformKt$onEach$$inlined$unsafeTransform$1$2.a(SourceFile:88)
at kotlinx.coroutines.flow.FlowKt__ChannelsKt.a(SourceFile:130)
at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.x(SourceFile:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.j(SourceFile:6)
at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
at kotlinx.coroutines.EventLoop.r0(SourceFile:24)
at kotlinx.coroutines.CancellableContinuationImpl.s(SourceFile:84)
at kotlinx.coroutines.CancellableContinuationImpl.v(SourceFile:3)
at kotlinx.coroutines.channels.BufferedChannelKt.a(SourceFile:7)
at kotlinx.coroutines.channels.BufferedChannel.D(SourceFile:61)
at kotlinx.coroutines.channels.BufferedChannel.f(SourceFile:57)
at kotlinx.coroutines.channels.BufferedChannel.p(SourceFile:84)
at androidx.paging.PageFetcherSnapshot.f(SourceFile:453)
at androidx.paging.PageFetcherSnapshot$doInitialLoad$1.x(SourceFile:12)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.j(SourceFile:6)
at kotlinx.coroutines.DispatchedTask.run(SourceFile:116)
at android.os.Handler.handleCallback(Handler.java:942)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7927)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:941)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [LazyStandaloneCoroutine{Cancelling}@7142c3e, Dispatchers.Main.immediate]
</details>

**Comment by nikclayton** [comment]
Thanks for the report, and for testing Pachli Current. This is exactly the sort of problem I was hoping to shake out of this particular release.

What server are you on? I can see it's crashing because there is a post in your timeline that has a preview card without an "html" property.

That's supposed to be mandatory (https://docs.joinmastodon.org/entities/PreviewCard/#html). I can work around this in Pachli, but knowing which server it is will let me contact the authors and report the bug to them so it will eventually be fixed on their side too.

**Comment by foss-** [comment]
Friendica accounts:

This is Friendica, version 2024.03-dev that is running at the web location https://squeet.me. The database version is 1552/1552, the post update version is 1547/1550.

This is Friendica, version 2024.03-dev that is running at the web location https://pirati.ca. The database version is 1552/1552, the post update version is 1550/1550.

**Comment by nikclayton** [comment]
Thanks. I reported this as https://github.com/friendica/friendica/issues/13887, and will add a workaround in Pachli.
