### ISSUE TITLE
Sharing link to post crashes the app

### ISSUE THREAD

**Issue by fourlastor** [pachli/pachli-android#700]
**Describe the bug**

Whenever I try using the "share link to post" the app crashes.

**To Reproduce**
1. Open the app
2. Click on the 3 dots button to the bottom right of any post
3. Select "Share link to post"
4. The app crashes

**Expected behavior**

The app correctly shows the share interface

**Screenshots or video**

https://github.com/pachli/pachli-android/assets/1263058/94337ba9-d6b6-4050-b284-f8704137b053

**Versions**

Pachli 2.5.1
Google Pixel 3a
Android 12
SDK level 32

**Additional context**

Sometimes the following popup appears when the app crashes

![image](https://github.com/pachli/pachli-android/assets/1263058/bb48d5c8-c34f-4515-92ed-79fc5df4127b)

**Affirmation**
I have checked other issues for this project (open and closed) and I cannot find one that matches the problem I am reporting.

**Comment by nikclayton** [comment]
Hmm. Just tried to reproduce and it works ok for me. Can you try with Pachli Current and see if that prompts you to send a crash report?

**Comment by fourlastor** [comment]
I couldn't get the crash report via the error report but apparently I can see it in LogCat!

```
2024-05-17 16:12:50.356  6057-6057  AndroidRuntime          android                              E  FATAL EXCEPTION: main
Process: android:ui, PID: 6057
java.lang.RuntimeException: Unable to start activity ComponentInfo{android/com.android.internal.app.ChooserActivity}: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = app.pachli.core.activity.extensions.TransitionKind)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3707)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:201)
at android.os.Looper.loop(Looper.java:288)
at android.app.ActivityThread.main(ActivityThread.java:7870)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
Caused by: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = app.pachli.core.activity.extensions.TransitionKind)
at android.os.Parcel.readSerializable(Parcel.java:3513)
at android.os.Parcel.readValue(Parcel.java:3277)
at android.os.Parcel.readArrayMapInternal(Parcel.java:3623)
at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
at android.os.BaseBundle.unparcel(BaseBundle.java:236)
at android.os.Bundle.getParcelable(Bundle.java:1002)
at android.content.Intent.getParcelableExtra(Intent.java:8548)
at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:607)
at android.app.Activity.performCreate(Activity.java:8054)
at android.app.Activity.performCreate(Activity.java:8034)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7870) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
Caused by: java.lang.ClassNotFoundException: app.pachli.core.activity.extensions.TransitionKind
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:536)
at android.os.Parcel$2.resolveClass(Parcel.java:3499)
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1733)
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1624)
at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1854)
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1439)
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:430)
at android.os.Parcel.readSerializable(Parcel.java:3507)
at android.os.Parcel.readValue(Parcel.java:3277) 
at android.os.Parcel.readArrayMapInternal(Parcel.java:3623) 
at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
at android.os.Bundle.getParcelable(Bundle.java:1002) 
at android.content.Intent.getParcelableExtra(Intent.java:8548) 
at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:607) 
at android.app.Activity.performCreate(Activity.java:8054) 
at android.app.Activity.performCreate(Activity.java:8034) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7870) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
Caused by: java.lang.ClassNotFoundException: app.pachli.core.activity.extensions.TransitionKind
at java.lang.Class.classForName(Native Method) 
at java.lang.Class.forName(Class.java:536) 
at android.os.Parcel$2.resolveClass(Parcel.java:3499) 
at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1733) 
at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1624) 
at java.io.ObjectInputStream.readEnum(ObjectInputStream.java:1854) 
at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1439) 
at java.io.ObjectInputStream.readObject(ObjectInputStream.java:430) 
at android.os.Parcel.readSerializable(Parcel.java:3507) 
at android.os.Parcel.readValue(Parcel.java:3277) 
at android.os.Parcel.readArrayMapInternal(Parcel.java:3623) 
at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292) 
at android.os.BaseBundle.unparcel(BaseBundle.java:236) 
at android.os.Bundle.getParcelable(Bundle.java:1002) 
at android.content.Intent.getParcelableExtra(Intent.java:8548) 
at com.android.internal.app.ChooserActivity.onCreate(ChooserActivity.java:607) 
at android.app.Activity.performCreate(Activity.java:8054) 
at android.app.Activity.performCreate(Activity.java:8034) 
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1341) 
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3688) 
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3864) 
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103) 
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:201) 
at android.os.Looper.loop(Looper.java:288) 
at android.app.ActivityThread.main(ActivityThread.java:7870) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)  
```

**Comment by nikclayton** [comment]
Thanks. That should be straightforward to fix when I'm back (~ 2 weeks).

I'm a bit confused as to why it doesn't manifest in the Pachli Current build I'm running though. I'll investigate further when I'm back.

**Comment by guntbert** [comment]
I just found a workaround:
Instead of selecting 'share' I select 'copy' and then my Android offers the sharing symbol, which works without crashing.

Pachli 2.5.1

Device:

Google Pixel 6a
Android version: 14
SDK level: 34
